on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  running_test:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Speeding-up by Restoring Gradle Cache from Previous Builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*')}}
          restore-keys: |
            ${{runner.os}}-gradle-
      - name: Unit tests
        run: bash ./gradlew test --stacktrace


  lint_job:
    name: kLint task
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Ktlint format
        run: bash ./gradlew ktlintFormat --stacktrace

      - name: KtLint task
        run: bash ./gradlew ktlint --stacktrace
